### PR TITLE
use decltype for lambda return type deduction in Boost if available

### LINKED ISSUE #111: Build error on openSUSE in examples/osmium_convert.cpp
CMake output:

-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_KEEP_INLINE_FUNCTIONS
-- Performing Test HAS_KEEP_INLINE_FUNCTIONS - Success
-- Boost version: 1.53.0
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found EXPAT: /usr/lib64/libexpat.so (found version "2.1.0") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
-- Found GDAL: /usr/lib64/libgdal.so  
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of google::sparsetable<int>::size_type
-- Check size of google::sparsetable<int>::size_type - done
-- Found Osmium: include  
-- Use C++ version: c++11
-- Configuring unit tests
-- Configuring unit tests - done
-- Looking for cppcheck
-- Looking for cppcheck - not found
--   Build target 'cppcheck' will not be available.
-- Configuring examples
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   program_options
-- Configuring examples - Building these examples:
--   - osmium_area_test
--   - osmium_convert
--   - osmium_count
--   - osmium_create_node_cache
--   - osmium_debug
--   - osmium_index
--   - osmium_read
--   - osmium_serdump
--   - osmium_toogr
--   - osmium_toogr2
--   - osmium_toogr2_exp
--   - osmium_use_node_cache
-- Configuring examples - done
-- Configuring documentation
-- Looking for doxygen
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") 
-- Looking for doxygen - found
-- Configuring documentation - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eike/repos/build/osmium
$ make osmium_convert 2>&1 | head -n 20
[ 50%] Building CXX object examples/CMakeFiles/osmium_convert.dir/osmium_convert.cpp.o
In file included from /usr/include/boost/iterator/transform_iterator.hpp:23:0,
                 from /home/eike/repos/OSM/libosmium/include/osmium/io/detail/pbf_output_format.hpp:50,
                 from /home/eike/repos/OSM/libosmium/include/osmium/io/pbf_output.hpp:46,
                 from /home/eike/repos/OSM/libosmium/include/osmium/io/any_output.hpp:50,
                 from /home/eike/repos/OSM/libosmium/examples/osmium_convert.cpp:14:
/usr/include/boost/utility/result_of.hpp: In instantiation of ‘struct boost::detail::result_of_nested_result<const osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23, const osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23(const osmium::RelationMember&)>’:
/usr/include/boost/utility/result_of.hpp:170:8:   required from ‘struct boost::detail::tr1_result_of_impl<const osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23, const osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23(const osmium::RelationMember&), false>’
/usr/include/boost/utility/detail/result_of_iterate.hpp:27:8:   required from ‘struct boost::tr1_result_of<const osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23(const osmium::RelationMember&)>’
/usr/include/boost/utility/detail/result_of_iterate.hpp:146:8:   required from ‘struct boost::result_of<const osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23(const osmium::RelationMember&)>’
/usr/include/boost/mpl/eval_if.hpp:38:31:   required from ‘struct boost::mpl::eval_if<boost::is_same<boost::use_default, boost::use_default>, boost::result_of<const osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23(const osmium::RelationMember&)>, boost::mpl::identity<boost::use_default> >’
/usr/include/boost/iterator/iterator_adaptor.hpp:160:12:   required from ‘struct boost::detail::ia_dflt_help<boost::use_default, boost::result_of<const osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23(const osmium::RelationMember&)> >’
/usr/include/boost/iterator/transform_iterator.hpp:50:17:   required from ‘struct boost::detail::transform_iterator_base<osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23, osmium::memory::CollectionIterator<const osmium::RelationMember>, boost::use_default, boost::use_default>’
/usr/include/boost/iterator/transform_iterator.hpp:74:9:   required from ‘class boost::transform_iterator<osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23, osmium::memory::CollectionIterator<const osmium::RelationMember>, boost::use_default, boost::use_default>’
/home/eike/repos/OSM/libosmium/include/osmium/io/detail/pbf_output_format.hpp:547:99:   required from here
/usr/include/boost/utility/result_of.hpp:166:8: error: no class template named ‘result’ in ‘const struct osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23’
 struct result_of_nested_result : F::template result<FArgs>
        ^
In file included from /usr/include/boost/iterator/iterator_categories.hpp:15:0,
                 from /usr/include/boost/iterator/iterator_adaptor.hpp:14,

### PR DESCRIPTION
**Pull request by DerDakon**
This allows osmium_convert to be build even with older Boost versions if the
compiler is new enough, otherwise one may get a build error like this:

/usr/include/boost/utility/result_of.hpp:166:8: error: no class template named ‘result’ in ‘const struct osmium::io::detail::PBFOutputFormat::relation(const osmium::Relation&)::__lambda23’
 struct result_of_nested_result : F::template result<FArgs>
        ^

This fixes #111 for me.

### CODE REVIEW

**Comment by joto** [comment]
Hm. Do I understand it correctly that this only works in CMake 3.1 and above? I would expect somebody who has such a new CMake version also to have a current Boost library.

**Comment by DerDakon** [comment]
CMake is easier to upgrade as it is just a binary and does not affect programs possibly linked against it. OTOH it will allow anyone with a recent enough gcc to just use decltype instead of any Boost magic, even with newer Boost versions.

**Comment by joto** [comment]
Newer boost versions do the right magic automatically. I have documented that you should use at least 1.55. I also just added a `#define BOOST_RESULT_OF_USE_DECLTYPE` because it doesn't hurt in any case. Easier than your cmake magic.
