### ISSUE TITLE
Fails to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by ihor-nahuliak** [osmcode/libosmium#267]
The error step is here:
```
[ 58%] Linking CXX executable io_test_pbf
CMakeFiles/io_test_pbf.dir/t/io/test_pbf.cpp.o: In function `osmium::io::detail::decode_blob(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/home/undefined/work/kvadom/libosmium/include/osmium/io/detail/zlib.hpp:108: undefined reference to `uncompress'
/home/undefined/work/kvadom/libosmium/include/osmium/io/detail/zlib.hpp:111: undefined reference to `zError'
CMakeFiles/io_test_pbf.dir/t/io/test_pbf.cpp.o: In function `void std::vector<std::thread, std::allocator<std::thread> >::_M_realloc_insert<void (osmium::thread::Pool::*)(), osmium::thread::Pool*>(__gnu_cxx::__normal_iterator<std::thread*, std::vector<std::thread, std::allocator<std::thread> > >, void (osmium::thread::Pool::*&&)(), osmium::thread::Pool*&&)':
/usr/include/c++/7/thread:126: undefined reference to `pthread_create'
CMakeFiles/io_test_pbf.dir/t/io/test_pbf.cpp.o: In function `osmium::thread::Pool::Pool(int, unsigned long)':
/usr/include/c++/7/thread:126: undefined reference to `pthread_create'
CMakeFiles/io_test_pbf.dir/t/io/test_pbf.cpp.o: In function `osmium::io::Reader::Reader<>(osmium::io::File const&)':
/usr/include/c++/7/thread:126: undefined reference to `pthread_create'
/usr/include/c++/7/thread:126: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
test/CMakeFiles/io_test_pbf.dir/build.make:95: recipe for target 'test/io_test_pbf' failed
make[2]: *** [test/io_test_pbf] Error 1
CMakeFiles/Makefile2:2360: recipe for target 'test/CMakeFiles/io_test_pbf.dir/all' failed
make[1]: *** [test/CMakeFiles/io_test_pbf.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

****  Installation failed. Aborting package creation.
```

**Comment by joto** [comment]
Well, it seems it doesn't find the zlib and pthread libraries. Have you installed all the dependencies as explained here: https://osmcode.org/libosmium/manual.html#dependencies ? Please post complete command lines you used as well as all output.

**Comment by ImreSamu** [comment]
@ihor-nahuliak : 
maybe helpful to you: 
see my full docker based log ( for  what you should expect on ubuntu:18:04 )
so you can compare - and check the differences yourself. 
https://gist.github.com/ImreSamu/24531a72d84b3c816dee95d56d43b83b

Don't forget removing the cmake project files, and check the cmake logs!
https://stackoverflow.com/questions/27247123/how-to-clean-up-the-project-files-generated-by-cmake/27254365

**Comment by adoerr** [comment]
I can confirm that after installing the dependencies mentioned in the manual the build works on Ubuntu 18.04. This is for the 'all' and the 'test' targets. So, you might want to close this issue.

**Comment by joto** [comment]
Yes, works for me too and the original reporter didn't supply requested information. Closing.

**Comment by utack** [comment]
Sorry to comment in here, but I did not want to open a new issue right away.
I am on Arch Linux and it seems like it can not find zlib 

> 
> >-- Found Osmium: /usr/include  
> -- Configuring done
> -- Generating done

```
: && /usr/bin/c++  -O3 -DNDEBUG  -rdynamic CMakeFiles/OSMini.dir/OSMini.cpp.o  -o OSMini   && :
/usr/bin/ld: CMakeFiles/OSMini.dir/OSMini.cpp.o: in function `osmium::io::detail::decode_blob(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
OSMini.cpp:(.text._ZN6osmium2io6detail11decode_blobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS7_[_ZN6osmium2io6detail11decode_blobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS7_]+0x263): undefined reference to `uncompress'
/usr/bin/ld: OSMini.cpp:(.text._ZN6osmium2io6detail11decode_blobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS7_[_ZN6osmium2io6detail11decode_blobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS7_]+0x2d7): undefined reference to `zError'
```
collect2: Fehler: ld gab 1 als Ende-Status zurück

**Comment by utack** [comment]
I am running into a similar problem using libosmium on Arch Linux
The aur package should have installed all dependencies, but somehow linking zlib seems to fail
Am I doing something wrong here?
Thank you for any help


CMakeLists

`cmake_minimum_required (VERSION 2.6)

project (OSMini)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")

find_package(Osmium REQUIRED COMPONENTS pbf)
if(NOT OSMIUM_FOUND)
    message(WARNING "Libosmium not found!\n")
endif()
include_directories(SYSTEM ${OSMIUM_INCLUDE_DIRS})

add_executable(OSMini OSMini.cpp)`

Build output:

```

Building in: /home/jakob/eclipse-workspace/OSMini/build/default
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON /home/jakob/eclipse-workspace/OSMini
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protozero: /usr/include (found suitable version "1.6.5", minimum required is "1.6.3") 
-- Found Osmium: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jakob/eclipse-workspace/OSMini/build/default
cmake --build . -- -v
[1/2] /usr/bin/c++  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -O3 -DNDEBUG -MD -MT CMakeFiles/OSMini.dir/OSMini.cpp.o -MF CMakeFiles/OSMini.dir/OSMini.cpp.o.d -o CMakeFiles/OSMini.dir/OSMini.cpp.o -c ../../OSMini.cpp
[2/2] : && /usr/bin/c++  -O3 -DNDEBUG  -rdynamic CMakeFiles/OSMini.dir/OSMini.cpp.o  -o OSMini   && :
FAILED: OSMini 
: && /usr/bin/c++  -O3 -DNDEBUG  -rdynamic CMakeFiles/OSMini.dir/OSMini.cpp.o  -o OSMini   && :
/usr/bin/ld: CMakeFiles/OSMini.dir/OSMini.cpp.o: in function `osmium::io::detail::decode_blob(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
OSMini.cpp:(.text._ZN6osmium2io6detail11decode_blobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS7_[_ZN6osmium2io6detail11decode_blobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS7_]+0x263): undefined reference to `uncompress'
/usr/bin/ld: OSMini.cpp:(.text._ZN6osmium2io6detail11decode_blobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS7_[_ZN6osmium2io6detail11decode_blobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS7_]+0x2d7): undefined reference to `zError'
collect2: Fehler: ld gab 1 als Ende-Status zurück
ninja: build stopped: subcommand failed.
```

**Comment by demiantres** [comment]
I came across the same problem. My fix was to use manually compile protozero instead of using the one shipped with Ubuntu.
