### ISSUE TITLE
Fails to build with GEOS 3.6.0

### ISSUE THREAD

**Issue by sebastic** [osmcode/libosmium#168]
Unfortunately libosmium also fails to build with GEOS 3.6.0 due to the GeometryFactory changes:

```
[ 49%] Building CXX object test/CMakeFiles/geom_test_geos.dir/t/geom/test_geos.cpp.o
cd /build/libosmium-2.9.0/build/test && /usr/bin/c++   -DOSMIUM_WITH_SPARSEHASH=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/build/libosmium-2.9.0/include -isystem /usr/include/gdal -I/build/libosmium-2.9.0/test/include  -g -O2 -fdebug-prefix-map=/build/libosmium-2.9.0=. -fstack-protector-strong -Wformat -Werror=format-security  -O3 -g   -std=c++11 -Wno-parentheses -o CMakeFiles/geom_test_geos.dir/t/geom/test_geos.cpp.o -c /build/libosmium-2.9.0/test/t/geom/test_geos.cpp
In file included from /build/libosmium-2.9.0/test/t/geom/test_geos.cpp:3:0:
/build/libosmium-2.9.0/include/osmium/geom/geos.hpp: In constructor 'osmium::geom::detail::GEOSFactoryImpl::GEOSFactoryImpl(int, int)':
/build/libosmium-2.9.0/include/osmium/geom/geos.hpp:121:101: error: 'geos::geom::GeometryFactory::GeometryFactory(const geos::geom::PrecisionModel*, int)' is protected within this context
                     m_our_geos_factory(new geos::geom::GeometryFactory(m_precision_model.get(), srid)),
                                                                                                     ^
In file included from /build/libosmium-2.9.0/include/osmium/geom/geos.hpp:57:0,
                 from /build/libosmium-2.9.0/test/t/geom/test_geos.cpp:3:
/usr/include/geos/geom/GeometryFactory.h:464:2: note: declared protected here
  GeometryFactory(const PrecisionModel* pm, int newSRID);
  ^~~~~~~~~~~~~~~
In file included from /build/libosmium-2.9.0/test/t/geom/test_geos.cpp:3:0:
/build/libosmium-2.9.0/include/osmium/geom/geos.hpp: In constructor 'osmium::geom::detail::GEOSFactoryImpl::GEOSFactoryImpl(int)':
/build/libosmium-2.9.0/include/osmium/geom/geos.hpp:127:101: error: 'geos::geom::GeometryFactory::GeometryFactory(const geos::geom::PrecisionModel*, int)' is protected within this context
                     m_our_geos_factory(new geos::geom::GeometryFactory(m_precision_model.get(), srid)),
                                                                                                     ^
In file included from /build/libosmium-2.9.0/include/osmium/geom/geos.hpp:57:0,
                 from /build/libosmium-2.9.0/test/t/geom/test_geos.cpp:3:
/usr/include/geos/geom/GeometryFactory.h:464:2: note: declared protected here
  GeometryFactory(const PrecisionModel* pm, int newSRID);
  ^~~~~~~~~~~~~~~
[ 49%] Linking CXX executable io_test_writer_with_mock_encoder
cd /build/libosmium-2.9.0/build/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/io_test_writer_with_mock_encoder.dir/link.txt --verbose=1
/usr/bin/c++   -g -O2 -fdebug-prefix-map=/build/libosmium-2.9.0=. -fstack-protector-strong -Wformat -Werror=format-security  -O3 -g   -Wl,-z,relro CMakeFiles/io_test_writer_with_mock_encoder.dir/t/io/test_writer_with_mock_encoder.cpp.o  -o io_test_writer_with_mock_encoder -rdynamic libtestlib.a -lexpat -lbz2 -lz -lpthread 
/build/libosmium-2.9.0/test/t/geom/test_geos.cpp: In function 'void ____C_A_T_C_H____T_E_S_T____27()':
/build/libosmium-2.9.0/test/t/geom/test_geos.cpp:28:33: error: 'geos::geom::GeometryFactory::GeometryFactory()' is protected within this context
     geos::geom::GeometryFactory geos_factory;
                                 ^~~~~~~~~~~~
In file included from /build/libosmium-2.9.0/include/osmium/geom/geos.hpp:57:0,
                 from /build/libosmium-2.9.0/test/t/geom/test_geos.cpp:3:
/usr/include/geos/geom/GeometryFactory.h:420:2: note: declared protected here
  GeometryFactory();
  ^~~~~~~~~~~~~~~
/build/libosmium-2.9.0/test/t/geom/test_geos.cpp:28:33: error: 'virtual geos::geom::GeometryFactory::~GeometryFactory()' is protected within this context
     geos::geom::GeometryFactory geos_factory;
                                 ^~~~~~~~~~~~
In file included from /build/libosmium-2.9.0/include/osmium/geom/geos.hpp:57:0,
                 from /build/libosmium-2.9.0/test/t/geom/test_geos.cpp:3:
/usr/include/geos/geom/GeometryFactory.h:474:10: note: declared protected here
  virtual ~GeometryFactory();
          ^
make[5]: Leaving directory '/build/libosmium-2.9.0/build'
[ 49%] Built target io_test_writer_with_mock_encoder
make -f test/CMakeFiles/basic_test_area.dir/build.make test/CMakeFiles/basic_test_area.dir/depend
make[5]: Entering directory '/build/libosmium-2.9.0/build'
cd /build/libosmium-2.9.0/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /build/libosmium-2.9.0 /build/libosmium-2.9.0/test /build/libosmium-2.9.0/build /build/libosmium-2.9.0/build/test /build/libosmium-2.9.0/build/test/CMakeFiles/basic_test_area.dir/DependInfo.cmake --color=
Dependee "/build/libosmium-2.9.0/build/test/CMakeFiles/basic_test_area.dir/DependInfo.cmake" is newer than depender "/build/libosmium-2.9.0/build/test/CMakeFiles/basic_test_area.dir/depend.internal".
Dependee "/build/libosmium-2.9.0/build/test/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/build/libosmium-2.9.0/build/test/CMakeFiles/basic_test_area.dir/depend.internal".
Scanning dependencies of target basic_test_area
make[5]: Leaving directory '/build/libosmium-2.9.0/build'
make -f test/CMakeFiles/basic_test_area.dir/build.make test/CMakeFiles/basic_test_area.dir/build
make[5]: Entering directory '/build/libosmium-2.9.0/build'
[ 50%] Building CXX object test/CMakeFiles/basic_test_area.dir/t/basic/test_area.cpp.o
cd /build/libosmium-2.9.0/build/test && /usr/bin/c++   -DOSMIUM_WITH_SPARSEHASH=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/build/libosmium-2.9.0/include -isystem /usr/include/gdal -I/build/libosmium-2.9.0/test/include  -g -O2 -fdebug-prefix-map=/build/libosmium-2.9.0=. -fstack-protector-strong -Wformat -Werror=format-security  -O3 -g   -std=c++11 -Wno-parentheses -o CMakeFiles/basic_test_area.dir/t/basic/test_area.cpp.o -c /build/libosmium-2.9.0/test/t/basic/test_area.cpp
In file included from /usr/include/c++/6/memory:81:0,
                 from /build/libosmium-2.9.0/test/include/catch.hpp:568,
                 from /build/libosmium-2.9.0/test/t/geom/test_geos.cpp:1:
/usr/include/c++/6/bits/unique_ptr.h: In instantiation of 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = geos::geom::GeometryFactory]':
/usr/include/c++/6/bits/unique_ptr.h:239:17:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = geos::geom::GeometryFactory; _Dp = std::default_delete<geos::geom::GeometryFactory>]'
/usr/include/c++/6/bits/unique_ptr.h:204:61:   required from 'constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr(std::nullptr_t) [with _Tp = geos::geom::GeometryFactory; _Dp = std::default_delete<geos::geom::GeometryFactory>; std::nullptr_t = std::nullptr_t]'
/build/libosmium-2.9.0/include/osmium/geom/geos.hpp:112:49:   required from here
/usr/include/c++/6/bits/unique_ptr.h:76:2: error: 'virtual geos::geom::GeometryFactory::~GeometryFactory()' is protected within this context
  delete __ptr;
  ^~~~~~
In file included from /build/libosmium-2.9.0/include/osmium/geom/geos.hpp:57:0,
                 from /build/libosmium-2.9.0/test/t/geom/test_geos.cpp:3:
/usr/include/geos/geom/GeometryFactory.h:474:10: note: declared protected here
  virtual ~GeometryFactory();
          ^
test/CMakeFiles/geom_test_geos.dir/build.make:62: recipe for target 'test/CMakeFiles/geom_test_geos.dir/t/geom/test_geos.cpp.o' failed
```

**Comment by joto** [comment]
The next version of libosmium will deprecate the use of GEOS. As far as I know, nobody is using it and the approach using the C++ API of GEOS is wrong anyway, because the GEOS project considers this to be internal and recommends use of the C API. I have added a check to the code which will disable building of the parts that use GEOS for versions from 3.6 onwards, so it shouldn't stand in the way of upgrading GEOS, but will keep working with older GEOS versions.

**Comment by mloskot** [comment]
> using the C++ API of GEOS is wrong anyway, because the GEOS project considers this to be internal

No quite, [it is public and supported interface](https://lists.osgeo.org/pipermail/geos-devel/2017-January/007653.html).

> and recommends use of the C API.

Yes, correct.
